# Generated by Django 5.0.6 on 2024-06-12 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LmsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('username', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('mobile', models.IntegerField(default=0, verbose_name='手机')),
                ('borrow_num', models.IntegerField(default=0, verbose_name='借书数量')),
                ('is_allow_borrow', models.BooleanField(default=True, verbose_name='是否允许借书')),
                ('class_major', models.CharField(max_length=32, verbose_name='专业-班级')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('addr', models.CharField(max_length=64, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='书名')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('publish_date', models.DateField(blank=True, max_length=64, verbose_name='出版日期')),
                ('catagoery', models.CharField(max_length=64, verbose_name='类别')),
                ('picture', models.ImageField(blank=True, upload_to='static/images', verbose_name='图片')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_managerment.publisher')),
            ],
        ),
    ]
