# Generated by Django 5.0.6 on 2024-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_managerment', '0002_administor_appointment_borrow_overdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=64, verbose_name='出版社'),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
