# Generated by Django 5.0.6 on 2024-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_managerment', '0005_alter_book_picture_alter_book_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否管理员'),
        ),
    ]
