# Generated by Django 5.0.6 on 2024-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_managerment', '0006_lmsuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
    ]
